[tool.isort]
profile = "black"
include_trailing_comma = false
line_length = 120

[tool.pylint.format]
good-names-rgxs = "^[_a-z][_a-z0-9]?$"
max-line-length = 120

[tool.pylint.messages_control]
disable = ["missing-docstring"]

[tool.ruff]
line-length = 120
