[tool.black]
line-length = 128
skip-string-normalization = true
target-version = ['py310']

[tool.isort]
profile = "black"
include_trailing_comma = false
line_length = 128

[tool.pylint.format]
good-names-rgxs = "^[_a-z][_a-z0-9]?$"
max-line-length = 128

[tool.pylint.messages_control]
disable = ["missing-docstring"]

[tool.yapf]
based_on_style = "google"
column_limit = 128
